### PR TITLE
translationWords refactor

### PR DESCRIPTION
**Pull request by mannycolon**
TODO:  BareTargetVerseDisplay

This PR changes the main component to be called from tC from View.js to Container.js

**Tests:
In order to tests this branch you may also have to get the updated proposedChanges component and the comment box component.**

This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/10)

### CODE REVIEW

**Comment by mannycolon** [comment]
@t3hpr1m3

**Comment by ihoegen** [comment]
Reviewed 3 of 16 files at r1, 11 of 21 files at r2.
Review status: 9 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/BareTargetVerseDisplay.js, line 2 at r2](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/10#-K_DIOwgCOTk1TtIKWsE:-K_DIOwgCOTk1TtIKWsF:bqqsive) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/7c5a0191b33ac1f11227b142bc48864cf08a5508/components/BareTargetVerseDisplay.js#L2)):*
> ```JavaScript
> /**
>  * A more organic implementation of the Target Verse Display
> ```

There still appears to be state in here. Can that be taken care of, or is state necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/10)*

**Comment by ihoegen** [comment]
Reviewed 1 of 16 files at r1, 10 of 21 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/10)*

**Comment by ihoegen** [comment]
```
TypeError: USFMParser is not a function
    at Door43DataFetcher.getULBFromBook (C:/Users/Ian/AppData/Roaming/translationCore/packages-compiled/translationWords/js/Door43DataFetcher.js:40:30)
    at getData (C:/Users/Ian/AppData/Roaming/translationCore/packages-compiled/translationWords/FetchData.js:106:30)
    at Object.getDataFromOnline (C:/Users/Ian/Documents/Work/tC/src/js/components/core/create_project/CheckDataGrabber.js:228:5)
    at saveModules (C:/Users/Ian/Documents/Work/tC/src/js/components/core/create_project/CheckDataGrabber.js:37:18)
    at Object.saveModules (C:/Users/Ian/Documents/Work/tC/src/js/components/core/create_project/CheckDataGrabber.js:67:7)
    at Object.fetchModules (C:/Users/Ian/Documents/Work/tC/src/js/components/core/create_project/CheckDataGrabber.js:31:12)
    at _this.createCheckArray (C:/Users/Ian/Documents/Work/tC/src/js/components/core/create_project/CheckDataGrabber.js:91:19)
    at Object.createCheckArray (C:/Users/Ian/Documents/Work/tC/src/js/components/core/create_project/CheckDataGrabber.js:126:9)
    at fs.readJson (C:/Users/Ian/Documents/Work/tC/src/js/components/core/create_project/CheckDataGrabber.js:89:15)
    at C:\Users\Ian\Documents\Work\tC\node_modules\fs-extra\node_modules\jsonfile\index.js:46:5
```

**Comment by mannycolon** [comment]
@ihoegen the USFMParser error happens because I'm using your USFMParser npm module is there anything different in that npm module from this one right here https://github.com/translationCoreApps/translationWords_Check_plugin/blob/master/Door43DataFetcher.js

**Comment by ihoegen** [comment]
The function you are looking for is I believe `USFMParser.toJson()`

**Comment by mannycolon** [comment]
@ihoegen can you test the **USFMParser** error again? I think I got it fixed now.

**Comment by ihoegen** [comment]
@mannycolon This is what I get when I run it

image
image

**Comment by ihoegen** [comment]
Reviewed 1 of 21 files at r2, 3 of 4 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/10)*

**Comment by ihoegen** [comment]
Reviewed 1 of 21 files at r2, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/10)*

**Pull request merged**
