### PR TITLE
Implement data persistence for module settings reducer

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

This PR recovers data persistence for the scripture pane settings.

#### How to test this pull request:
Test with https://github.com/unfoldingWord-dev/translationCore/pull/1046

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/64)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Code looks good. Just wondering why not take the approach of just adding a check inside ScripturePane fetch data for props.modulesSettingsReducer.ScripturePane instead of passing new parameters

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/64#-:-Kh4gfElUT6WzzC4PWZZ:b3j3xn9)*

**Comment by mannycolon** [comment]
@RoyalSix what do you mean?? you have to pass the parameter prop to scripturePaneData() function in order access it in the ScripturePane fetch data.

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/64)*

**Comment by RoyalSix** [comment]
@manncolon you are right! I forgot we weren't passing this.props to that function!

**Pull request merged**
