### PR TITLE
Shave some time on translationWords

### PR DESCRIPTION
**Pull request by ihoegen**
@mannycolon  or @RoyalSix

---

This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/1)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/1)*

**Comment by mannycolon** [comment]
@ihoegen Looks good I was just wondering how would I test this branch

**Comment by ihoegen** [comment]
@mannycolon Just copy it to packages-compiled folder

**Comment by ihoegen** [comment]
@mannycolon Actually, you can get away with opening packages compiled, and using git to checkout to my branch

**Pull request merged**
