### PR TITLE
Add Filters

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This pull request allows a CSV to be used to remove unneeded checks, as well as add previously missed checks. 

#### How to test this pull request:

I've changed the order of the fetch data so this can be tested. I don't exactly know how to test this, but a code review is helpful.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/65)

### CODE REVIEW

**Comment by mannycolon** [comment]
@RoyalSix I think it would be good if you review this PR since you have a lot of familiarity with these files. i just want to make sure that any of the changes don't affect the desired end result.

**Comment by mannycolon** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[FetchData/main.js, line 14 at r2](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/65#-Kh8Fh5xu3z_1o4wGPFg:-Kh8Fh5yKexADX6k7gyP:b-7s2643) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/148f6e1d3bf197ab495ecd389bcd722f2b5421b0/FetchData/main.js#L14)):*
> ```JavaScript
> 
>   return new Promise(function(resolve, reject) {
>     tWFetchData(projectDetails, bibles, actions, progress);
> ```

why change the order of operation??????

i would consukt with jay about this. also the logic is worng now with this change because the FETCH_DATAS_FINISHED IS UPDATING IN THE WRONG SEQUENCE.

---

*[FetchData/TranslationWords.js, line 178 at r2](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/65#-Kh8G00nX1G_xj1DuA1J:-Kh8G00nX1G_xj1DuA1K:b-bq4w5m) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/148f6e1d3bf197ab495ecd389bcd722f2b5421b0/FetchData/TranslationWords.js#L178)):*
> ```JavaScript
>       while (groupName) {
>         if (!checkIfWordsAreMarked(groupName, mappedVerseObject)) {
>           if (filter) {
> ```

can we add comments explaining whats happening 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/65)*

**Comment by ihoegen** [comment]
@mannycolon I fixed the order, and added comments

**Comment by klappy** [comment]
Reviewed 2 of 4 files at r1, 1 of 2 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/65)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/65#-:-KhSfgjAtWJYtNzAU-0d:bnfp4nl)*

**Comment by klappy** [comment]
Since I'm having a hard time testing for anomalies, I'm going to pull this and we'll ask Perry and his team to look for problems for us to address. Let's go ahead and get this one in.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/65#-:-KhT-VEpAbNh4N11bbnH:b-d0dbrf)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/65#-:-KhT-hWei7RGwSM2F8U1:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/65)*

**Pull request merged**
