### PR TITLE
Fix Changing Tools

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
Fixes the ability to change tools after initially choosing a tool
https://github.com/unfoldingWord-dev/translationCore/pull/1073

#### How to test this pull request:
Get a fresh project
checkout js_fixChangeProject on tC
load a tool and try switching

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/69)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Container.js, line 21 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/69#-KhUzbPI9VE6acgzFeK0:-KhUzbPI9VE6acgzFeK1:b-ey36v8) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/204acc2670d6c6f11b0e53b74a076d72c71e9018/Container.js#L21)):*
> ```JavaScript
> 
>   componentWillMount() {
>     FetchData(this.props).then(this.props.actions.doneLoading);
> ```

great job!

---

*[Container.js, line 26 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/69#-KhUzWVpZuaTzgzy6EYH:-KhUzWVpZuaTzgzy6EYI:bj9yx1j) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/204acc2670d6c6f11b0e53b74a076d72c71e9018/Container.js#L26)):*
> ```JavaScript
> 
>   componentWillReceiveProps(nextProps) {
>     if (!nextProps.currentToolReducer.dataFetched) {
> ```

just wanted to know the reason why you added this code here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/69)*

**Comment by RoyalSix** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Container.js, line 21 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/69#-KhUzbPI9VE6acgzFeK0:-Khau5hMnEWdrUyMc7QS:b-896fix) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/204acc2670d6c6f11b0e53b74a076d72c71e9018/Container.js#L21)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

great job!
</blockquote></details>

Done.

---

*[Container.js, line 26 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/69#-KhUzWVpZuaTzgzy6EYH:-Khau2sN0Kg9YQfLMxLJ:b-896fix) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/204acc2670d6c6f11b0e53b74a076d72c71e9018/Container.js#L26)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

just wanted to know the reason why you added this code here. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/69)*

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/69)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/69#-:-Khce41HVqQI---BagiC:bnfp4nl)*

**Pull request merged**
