### PR TITLE
Ability to toggle display of translation helps

### PR DESCRIPTION
**Pull request by EllDoubleYew**
#### This pull request addresses:
This PR addresses #762 in the main repo

#### How to test this pull request:

Click the new tab hanging on the right side of the translation helps section to hide or show translation helps.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/40)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/40)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[View.js, line 112 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/40#-KeaBsefoTWgMFWKH_Xg:-KeaBsefoTWgMFWKH_Xh:b-2ho1p0) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/c1c500dcb18a0cc8f8515d95664158584bbbff2c/View.js#L112)):*
> ```JavaScript
>               </Tabs>
>             </Col>
>           <Col sm={12} md={6} lg={4} style={{padding: "0px", backgroundColor: this.props.showHelps ? "" : "#fff"}}>
> ```

You shouldn't have to change the background color. why are you doing that??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/40)*

**Comment by EllDoubleYew** [comment]
@mannycolon if I dont it will be #333333 space instead of whitespace 😅. I can revert it back to gray if you would like.

**Comment by mannycolon** [comment]
@EllDoubleYew that's weird. it should show what's behind it, which should be white.

**Comment by ihoegen** [comment]
Yeah so both of these PRs shift everything up on initial load, and I can't find the arrow to toggle back everything. 
image
image

**Comment by mannycolon** [comment]
@elldoubleyew when I hide the tHelps i can't get  it back since the chevron goes away and i can't see it

**Comment by mannycolon** [comment]
@ihoegen I merged master with this branch. that should fixed the layout shift bug but the chevron still goes away. and cant get thelps back

**Pull request merged**
