### PR TITLE
Update Word List and add script for ease

### PR DESCRIPTION
**Pull request by ihoegen**
When testing this, try clicking on the links as well. No need to test the script, just make sure sources look good.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/24)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/UpdateWordList.js, line 7 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/24#-KbOKmQcEQr3aybZYvvb:-KbOKmQcEQr3aybZYvvc:b-p5kt3b) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/92b4ef09884808ec9513375ab6665d221755d1a1/scripts/UpdateWordList.js#L7)):*
> ```JavaScript
> var wordList = require('../static/WordList.json').wordList;
> var availableFiles = fs.readdirSync('./scripts/words');
> // console.log(availableFiles);
> ```

do you need this here??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/24)*

**Comment by mannycolon** [comment]
@ihoegen I dont quite understand what actually had been changed by this PR. I pulled this branch to my local tC repo  and when opened the tool the resources in the translationHelps looked the same as before. no links anywhere.

**Comment by ihoegen** [comment]
@mannycolon Make sure you delete your checkdata

**Comment by ihoegen** [comment]
# Before 

image

# After
image

Note the links as well, a PR on tC will make them open in new tabs.

**Comment by mannycolon** [comment]
@ihoegen awesome job ian

**Comment by mannycolon** [comment]
let me see if i can actually test the branch

**Pull request merged**
