### PR TITLE
Add target language to reports

### PR DESCRIPTION
**Pull request by ihoegen**
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/28)

### CODE REVIEW

**Comment by ihoegen** [comment]
@mannycolon Fixed conflicts

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Container.js, line 42 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/28#-Kc-Pwabpm1kWEGzl7gg:-Kc-Pwabpm1kWEGzl7gh:b41hk1q) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/1dc793596863c5a811a10e24f37fd08dc49d3971/Container.js#L42)):*
> ```JavaScript
> 
>   addTargetLanguageToChecks() {
>     let groups = api.getDataFromCheckStore(NAMESPACE, 'groups');
> ```

here you can do this.props.groups which is coming from the checkstoreReducer which is my redux implementation for the tools.

we want to limit the use of the API as much as we can from now on so have a smooth transition to redux as we go 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/28)*

**Comment by ihoegen** [comment]
@mannycolon Done

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/28)*

**Pull request merged**
