### PR TITLE
Add rules

### PR DESCRIPTION
**Pull request by ihoegen**
#### This pull request addresses:

This pull request allows for custom prespecified checks, via a CSV file.

#### How to test this pull request:

I don't believe fetch data is up and running yet, so only code review is needed.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/58)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Rules.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqU6ukt3Q7aqUqj2i1:-KgqU6ukt3Q7aqUqj2i2:br9ldcc) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/Rules.js#L5)):*
> ```JavaScript
> /**
>  *
>  * @param {string} bookName - The name of the book whose rule is being used
> ```

what does rule mean in this context?

---

*[Rules.js, line 11 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqVHxAuzC6Fpf03_yv:-KgqVHxAuzC6Fpf03_yw:b-ctk013) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/Rules.js#L11)):*
> ```JavaScript
>  */
> function getRules(bookName, wordList) {
>   var previousWord = '';
> ```

it seems you are doing a lot of work here that isn't required in this feature (#865r )

I really like you to demo your work.

Again, i could be wrong but i see a lot of parsing and a lot of code that looks very similar to what we use to have before.

---

*[Rules.js, line 45 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqTzDHlfZA4dGCiIP-:-KgqTzDHlfZA4dGCiIP0:b-sy54oe) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/Rules.js#L45)):*
> ```JavaScript
>     }
>     groups[currentItem[5]].push({
>       "chapter": currentItem[1],
> ```

what do you need this data structure for?

looks like the old data structure. 

---

*[FetchData/TranslationWords.js, line 49 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqULb-SRsMeaywNgD3:-KgqULb-SRsMeaywNgD4:b-nbsdhv) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/FetchData/TranslationWords.js#L49)):*
> ```JavaScript
>           var rules = fs.readdirSync(path.join(__dirname, 'rules'));
>           if (rules.includes(convertToFullBookName(params.bookAbbr) + '.csv')) {
>             setGroupsIndex(getRules(convertToFullBookName(params.bookAbbr), wordList));
> ```

what is the getRules() function actually doing in this case??

---

*[rules/Ephesians.csv, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqV4Vo4nikVn89i5rz:-KgqV4VpFFHLjV9jNdi4:bdv918u) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/rules/Ephesians.csv#L1)):*
> ```CSV
> Ephesians,1,1,in Christ,inchrist.txt," in Christ, in Jesus, in the Lord, in him ","Paul, an apostle of Christ Jesus through the will of God, to those who are set apart for God in Ephesus and who are faithful in Christ Jesus. Some early versions omit, in Ephesus, but this expression is probably in Paul's original letter."
> ```

what is this file and how are you using it??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58)*

**Comment by ihoegen** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Rules.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqU6ukt3Q7aqUqj2i1:-KgrTH1-nieZhqSQ0zOv:bpi89x0) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/Rules.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

what does rule mean in this context?
</blockquote></details>

Rule is a set of checks that have already been predefined. So instead of parsing any data, it uses a CSV file. 

---

*[Rules.js, line 11 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqVHxAuzC6Fpf03_yv:-KgrTM_0O_6ScQN7wzBJ:buk2sm) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/Rules.js#L11)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

it seems you are doing a lot of work here that isn't required in this feature (#865r )

I really like you to demo your work.

Again, i could be wrong but i see a lot of parsing and a lot of code that looks very similar to what we use to have before.
</blockquote></details>

What this code does is it reads in a CSV files, based on the checks that were identified as priority. From there, it loads them in as a group. There is a little bit of overlap in the code, but it's not enough to allow us to plug and play.

---

*[Rules.js, line 45 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqTzDHlfZA4dGCiIP-:-KgrTfPeXYIcy8MHjx7Z:b91m9tt) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/Rules.js#L45)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

what do you need this data structure for?

looks like the old data structure. 
</blockquote></details>

It is the old group data structure, I am waiting for a clear idea of what the new one looks like, but the fetch data does not run for some reason. 

---

*[FetchData/TranslationWords.js, line 49 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqULb-SRsMeaywNgD3:-KgrTltoL51CMaQuzDnS:b-ehw7tj) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/FetchData/TranslationWords.js#L49)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

what is the getRules() function actually doing in this case??
</blockquote></details>

Get rules returns the groups for the book. 

---

*[rules/Ephesians.csv, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqV4Vo4nikVn89i5rz:-KgrTpC-_p8ZuxEhycCM:b-l6piuc) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/rules/Ephesians.csv#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

what is this file and how are you using it??
</blockquote></details>

This is the checks for a chapter. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58)*

**Comment by mannycolon** [comment]
we can't merge this yet. we need to talk further about your implementation.

**Comment by klappy** [comment]
*[rules/Ephesians.csv, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-KgqV4Vo4nikVn89i5rz:-KgyibsHmL6usS39XDoF:byebgor) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/a69a3207c9e6ec9c0e06234011e207708f95370c/rules/Ephesians.csv#L1)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

This is the checks for a chapter. 
</blockquote></details>

Where are the True/False columns for if it is a false positive or false negative?
These are suppose to be the rules for generating a list of bad checks.
We generate the checks via searching, and then we use a list like this to be the filter for bad checks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58)*

**Comment by klappy** [comment]
Where are the True/False columns for if it is a false positive or false negative?
These are suppose to be the rules for generating a list of bad checks.
We generate the checks via searching, and then we use a list like this to be the filter for bad checks.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/58#-:-Kgyj-glKvgpXBUz0NMV:bv6jov)*

**Comment by ihoegen** [comment]
@klappy What about the cases where we need to add a check?

**Pull request closed without merging**
