### PR TITLE
Added Persistence To Groups Data 

### PR DESCRIPTION
**Pull request by RoyalSix**
https://github.com/unfoldingWord-dev/translationCore/pull/1063

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/68)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[FetchData/main.js, line 19 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68#-KhSbn3eCb0HNuhwcHhI:-KhSbn3eCb0HNuhwcHhJ:b-m5fb1h) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/e9e2ebe829b592ff0ad3d8c7182e270146ab9f5b/FetchData/main.js#L19)):*
> ```JavaScript
>     .then(()=>{
>       FETCH_DATAS_FINISHED++;
>       tWFetchData(projectDetails, bibles, actions, progress, groupsIndexLoaded, groupsDataLoaded);
> ```

I thought that tWFetchData shouldn't run if  groupsIndexLoaded and groupsDataLoaded were true so shouldn't we just do that if here right before calling this function?? 

or is there any code inside this function hat we still need it to run??

---

*[FetchData/TranslationWords.js, line 304 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68#-KhScGGlOiVrL7yZki3O:-KhScGGlOiVrL7yZki3P:blrc3l) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/e9e2ebe829b592ff0ad3d8c7182e270146ab9f5b/FetchData/TranslationWords.js#L304)):*
> ```JavaScript
>     var indexList = [];
>     var checkObj = {};
>     if (!groupsIndexLoaded || !groupsDataLoaded) {
> ```

ok i see ........ youre basically checking if one of them fail to load and them you loaded if so sounds like a great idea. I guess that's why you did not add the if checking main.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68)*

**Comment by mannycolon** [comment]
@RoyalSix please fix merge conflicts

**Comment by RoyalSix** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[FetchData/main.js, line 19 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68#-KhSbn3eCb0HNuhwcHhI:-Khaot77jkzHCZKwmYCY:b5ut5zx) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/e9e2ebe829b592ff0ad3d8c7182e270146ab9f5b/FetchData/main.js#L19)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I thought that tWFetchData shouldn't run if  groupsIndexLoaded and groupsDataLoaded were true so shouldn't we just do that if here right before calling this function?? 

or is there any code inside this function hat we still need it to run??
</blockquote></details>

It may need to get the gatewayLanguage

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68)*

**Comment by RoyalSix** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[FetchData/TranslationWords.js, line 304 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68#-KhScGGlOiVrL7yZki3O:-Khap10ltho7DRqXevu5:b2nhswy) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/e9e2ebe829b592ff0ad3d8c7182e270146ab9f5b/FetchData/TranslationWords.js#L304)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ok i see ........ youre basically checking if one of them fail to load and them you loaded if so sounds like a great idea. I guess that's why you did not add the if checking main.js
</blockquote></details>

Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68#-:-Khcki_UGywPUa1GIFB6:bnfp4nl)*

**Comment by klappy** [comment]
Code looked good but when I'm testing, I have an issue for getting `js_groups` to work. It works fine on first loading of a project without `apps` folder. Once we reload the project it does not load. it sits on `failed loading group data` on `GetDataActions.js`:310

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68#-:-Khcrz31ZSh2qXBd-NGv:bu0oe6n)*

**Comment by klappy** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/68)*

**Comment by mannycolon** [comment]
@RoyalSix @klappy after my fixes in develop this branch seems to work fine

**Pull request merged**
