### PR TITLE
drag to select component

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

This PR restructures bareTargetVerse component

**Refine Drag text selection method #724:**

-  #740 Abstract highlight rendering separate from selection 
- #738 Abstracted function for storing/appending selection
- #739 Abstracted function for removing selection
- #743 Abstract function for sending selection
- #737 Spike: Review New Data Structure for Text Selection

#### How to test this pull request:

- Change settings to allow drag to select.
- Try selecting a word by highlighting it in the target verse text selection area.
- Try selecting multiple words.
- Try unselecting a word by clicking on the highlighted word.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/38)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/BareTargetVerseDisplay.js, line 48 at r4](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38#-KeKoF3XeVI1tYc34Ka0:-KeKoF3XeVI1tYc34Ka1:b-tq6sm1) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/c5058e192e026e3e73e8015ae6a0c3dad3609c1b/components/BareTargetVerseDisplay.js#L48)):*
> ```JavaScript
>       }
>       let currentCheck = this.props.currentCheck;
>       currentCheck.selectedText = SelectionHelpers.optimizeSelections(verseText, newSelectedTextArray);
> ```

comment here would help alot!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38)*

**Comment by klappy** [comment]
*[components/BareTargetVerseDisplay.js, line 48 at r4](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38#-KeKoF3XeVI1tYc34Ka0:-KeKt7f4u7plH3KhH_CV:bu51sxv) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/c5058e192e026e3e73e8015ae6a0c3dad3609c1b/components/BareTargetVerseDisplay.js#L48)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

comment here would help alot!
</blockquote></details>

How does this sound? 

// optimize the selections to address potential issues

If that works, I'll add it and push. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38)*

**Comment by klappy** [comment]
*[components/BareTargetVerseDisplay.js, line 48 at r4](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38#-KeKoF3XeVI1tYc34Ka0:-KeKuYh6vRuzLPR05S2D:b-c0rwv0) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/c5058e192e026e3e73e8015ae6a0c3dad3609c1b/components/BareTargetVerseDisplay.js#L48)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

How does this sound? 

// optimize the selections to address potential issues

If that works, I'll add it and push. 
</blockquote></details>

Other options are to use words like, normalize, clean, sanitize instead of optimize.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38)*

**Comment by RoyalSix** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/BareTargetVerseDisplay.js, line 48 at r4](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38#-KeKoF3XeVI1tYc34Ka0:-KeL3beTc5KYY_jTinZf:boge0h5) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/c5058e192e026e3e73e8015ae6a0c3dad3609c1b/components/BareTargetVerseDisplay.js#L48)):*
> feature/mc-drag-to-select
Yea that first comment is perfect!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38)*

**Comment by RoyalSix** [comment]
This PR looks good. I spent a good amount of time analyzing the functions, so I could more adequately review the logic. There is only one notable quirk that my cause trouble in a normal use case: Highlighting one word and then highlighting another that is behind that word. I know this was a prior bug, and can be addressed separately. Every thing else looks fine. The PR does meet the requirements that its specified for, so I can give my approval for merging.

---

Reviewed 2 of 2 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[utils/selectionHelpers.js, line 32 at r4](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38#-KeL6jkXmxPgy97HFpD8:-KeL3t1mFxUi87ccyDqF:b-87v4po) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/c5058e192e026e3e73e8015ae6a0c3dad3609c1b/utils/selectionHelpers.js#L32)):*
> ```JavaScript
>                           occurrences: rangeObject.occurrences
>                         })
>     rangeShift += beforeSelection.length
> ```

This function looks great! Also maybe a comment here would help, why are we adding a range shift again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38#-:-KeL5DQm8hfulU5rnk8B:b-gwlgcw)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/38)*

**Pull request merged**
