### PR TITLE
Js group data actions

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR allows us to run fetch datas and send progress to the core app.

#### How to test this pull request:
Try and load a tool. Right now the UI is getting blocked so you cannot check the progress but if you console app js you can confirm it is working.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/56)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Container.js, line 3 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/56#-KgeznomUZZe4Ejfe5fQ:-KgeznomUZZe4Ejfe5fR:bckmnj8) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/1f99447a96379dd0d0d06729b3e59ae0a2fcd50d/Container.js#L3)):*
> ```JavaScript
> import React from 'react';
> import View from './View.js';
> // import TranslationWordsFetchData from './FetchData';
> ```

can we completely remove this commented out code

---

*[Container.js, line 28 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/56#-KgezxeqtO0-SdU1XvFw:-KgezxeqtO0-SdU1XvFx:b-wjli76) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/1f99447a96379dd0d0d06729b3e59ae0a2fcd50d/Container.js#L28)):*
> ```JavaScript
>   componentWillMount() {
>     let { resourcesReducer, projectDetailsReducer, actions } = this.props;
>     let { progress, addNewBible, addNewResource, setModuleSettings, addGroupData, addGroupIndex } = actions;
> ```

 let { resourcesReducer, projectDetailsReducer, actions } = this.props;
    let { progress, addNewBible, addNewResource, setModuleSettings, addGroupData, addGroupIndex } = actions;
let props = {
      params: projectDetailsReducer.params,
      manifest: projectDetailsReducer.manifest,
      bibles: resourcesReducer.bibles
    };

since your are sending the prosp directly to the FetchData function we can remove all of this code 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/56)*

**Comment by mannycolon** [comment]
@RoyalSix Great Job!! just need to take a look at the comments/suggestions I left. it's awesome you were able to use Promises. 

 Another thing let move the scripture pane fetch data out of the scripture pane folder (repo) to the tool folder (repo). I believe it's the best way to do it because the way you're importing it only works because they are in the same directory but in the future if we moved to a package manager system this may not work. In addition, I think keeping all the fetch datas in the tool brings a lot of benefits. for example, if they needed maintenance you only have to work in one repo. also, there's no reason to keep it in the scripture pane repo since the file is going to be call by the tool anyway. what do you think??

**Comment by RoyalSix** [comment]
I agree

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[Container.js, line 3 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/56#-KgeznomUZZe4Ejfe5fQ:-KgksO3fkJiT9e4FtnL9:b-896fix) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/1f99447a96379dd0d0d06729b3e59ae0a2fcd50d/Container.js#L3)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we completely remove this commented out code
</blockquote></details>

Done.

---

*[Container.js, line 28 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/56#-KgezxeqtO0-SdU1XvFw:-KgksTo4SW_CHhk_WmyA:b-896fix) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/1f99447a96379dd0d0d06729b3e59ae0a2fcd50d/Container.js#L28)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

 let { resourcesReducer, projectDetailsReducer, actions } = this.props;
    let { progress, addNewBible, addNewResource, setModuleSettings, addGroupData, addGroupIndex } = actions;
let props = {
      params: projectDetailsReducer.params,
      manifest: projectDetailsReducer.manifest,
      bibles: resourcesReducer.bibles
    };

since your are sending the prosp directly to the FetchData function we can remove all of this code 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/56#-:-KgksW1x9PBHi89MZjcn:b-cstnkg)*

**Comment by mannycolon** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/56)*

**Pull request merged**
