### PR TITLE
ULB Loaded Dynamically

### PR DESCRIPTION
**Pull request by RoyalSix**
The files are in the static folder for the check

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/2)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/2)*

**Comment by mannycolon** [comment]
testing branch

**Comment by ihoegen** [comment]
@RoyalSix I like the idea of the submodules, I will need to modify my clone command (easy to do) so that that data is downloaded as well.

**Comment by ihoegen** [comment]
Howerver, there is an issue with your submodule inclusion.

**Comment by RoyalSix** [comment]
Ok, I didn't realize I did that. Does that work? @ihoegen

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/2#-:-KW0I_hwj-BwDy1XjHqk:bjp10nm)*

**Comment by ihoegen** [comment]
@RoyalSix Basically, when I try to run it, I get an error pertaining to static/Door43. Here's the folder location: https://github.com/translationCoreApps/translationWords_Check_plugin/tree/js_ulb_door43/static

Basically git is treating this folder as a submodule. When I try to install it as a submodule, it can't find it.

**Comment by RoyalSix** [comment]
I see where github is treating it as a submodule now, I can't even navigate to it in the codebase on github. I did this unknowingly. I am going to merely delete any signs of git in that folder so that it can be included as a regular folder. This type of implementation might be something to look into in the future tho. Interesting.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/2#-:-KW1VM7Av3qLScziFoBW:b-50z0ys)*

**Pull request merged**
