### PR TITLE
fetch data redux

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

using new actions to add resources to the resourcesReducer through fetchdata.js

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/49)

### CODE REVIEW

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[FetchData.js, line 30 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/49#-KfjCHAxIhluc1HLkISu:-KfjCHAxIhluc1HLkISv:bjbn4uj) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/6b6f15eacbf5be34550d58a0ee8706778df6f3fc/FetchData.js#L30)):*
> ```JavaScript
> * @param {function} callback - callback that gets called when function is finished,
> * if error ocurred it's called with an error, 2nd argument carries the result
> * @param {callback} addNewBible - redux action to save a bible to
> ```

I don't think callback is a type, maybe function instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/49)*

**Comment by EllDoubleYew** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/49)*

**Comment by mannycolon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[FetchData.js, line 30 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/49#-KfjCHAxIhluc1HLkISu:-KflxOaXSIZkDbdtasDP:b-896fix) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/6b6f15eacbf5be34550d58a0ee8706778df6f3fc/FetchData.js#L30)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I don't think callback is a type, maybe function instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/49)*

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/49)*

**Pull request merged**
