### PR TITLE
VerseCheck

### PR DESCRIPTION
**Pull request by klappy**
This PR should be up to date with Manny’s latest PR’s and Check Info pane. 

**This PR addresses:**
Integration of VerseCheck component/module Abstraction.

**To test this PR**
Checkout VerseCheck repo to tC_apps folder, and run the app and see how it behaves. Please document here any other modifications you need to do to get the tool up and running with VerseCheck.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/46)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[View.js, line 19 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-Kf8_kPnsGNhOX2ed3mA:-Kf8_kPnsGNhOX2ed3mB:b-xuev99) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/81e60aa953f4e79169582e00c9a283dc6fe46c64/View.js#L19)):*
> ```JavaScript
>         <Row className="show-grid" style={{margin: '0px', bottom: "0px",  height: "100%"}}>
>           <Col sm={12} md={6} lg={9} style={{height: "100%", padding: '0px'}}>
>             <ScripturePane currentCheck={this.props.currentCheck} />
> ```

scripturePane requires {...this.props}
so  <ScripturePane {...this.props} currentCheck={this.props.currentCheck} />

---

*[View.js, line 22 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-Kf8a0s2ZFzMFvpkPdKC:-Kf8a0s2ZFzMFvpkPdKD:b-fez2rj) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/81e60aa953f4e79169582e00c9a283dc6fe46c64/View.js#L22)):*
> ```JavaScript
>             <CheckInfoCard openHelps={this.props.toggleHelps} showHelps={this.props.showHelps} title={this.props.currentCheck.phrase} file={this.props.currentFile}/>
>             <VerseCheck
>               updateCheckStatus={this.props.updateCheckStatus.bind(this)}
> ```

I'm not sure you have to bind(this) in this case

---

*[View.js, line 23 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-Kf8a5GLQblJ-xfU1mDh:-Kf8a5GLQblJ-xfU1mDi:bnj7hl0) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/81e60aa953f4e79169582e00c9a283dc6fe46c64/View.js#L23)):*
> ```JavaScript
>             <VerseCheck
>               updateCheckStatus={this.props.updateCheckStatus.bind(this)}
>               updateCurrentCheck={this.props.updateCurrentCheck.bind(this)}
> ```

same as above

---

*[components/CheckInfoCard.js, line 42 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-Kf8aFY-2NSPEAoTKRph:-Kf8aFY-2NSPEAoTKRpi:byusapx) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/81e60aa953f4e79169582e00c9a283dc6fe46c64/components/CheckInfoCard.js#L42)):*
> ```JavaScript
>       return (
>         <div style={{margin: '10px'}}>
>         <Card zDepth={2} style={{ background: '#2196F3', padding: "20px"}}>
> ```

I think the other bg color was the correct one given by Thomas. I could be wrong though. but looking at the mockups checkInforCard has a different bg color from the other cards headings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46)*

**Comment by klappy** [comment]
*[View.js, line 22 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-Kf8a0s2ZFzMFvpkPdKC:-Kf8d33C7gcnh99W-bCD:b-teehm2) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/81e60aa953f4e79169582e00c9a283dc6fe46c64/View.js#L22)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I'm not sure you have to bind(this) in this case
</blockquote></details>

I can't remember why I did, I can remove them and see if they still function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46)*

**Comment by klappy** [comment]
*[View.js, line 19 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-Kf8_kPnsGNhOX2ed3mA:-Kf8d9d32MNnlLaDF7_X:b-yndrse) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/81e60aa953f4e79169582e00c9a283dc6fe46c64/View.js#L19)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

scripturePane requires {...this.props}
so  <ScripturePane {...this.props} currentCheck={this.props.currentCheck} />
</blockquote></details>

adding now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46)*

**Comment by klappy** [comment]
*[components/CheckInfoCard.js, line 42 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-Kf8aFY-2NSPEAoTKRph:-Kf8dCywwA48WJ9vzTi-:b-9udygl) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/81e60aa953f4e79169582e00c9a283dc6fe46c64/components/CheckInfoCard.js#L42)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I think the other bg color was the correct one given by Thomas. I could be wrong though. but looking at the mockups checkInforCard has a different bg color from the other cards headings.
</blockquote></details>

The other one was technically correct, but I went back and forth with him on the ones that had the best contrast for reading, I've compared on multiple displays and projectors and this one seems to be easiest to read even on bad displays.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46)*

**Comment by klappy** [comment]
*[View.js, line 22 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-Kf8a0s2ZFzMFvpkPdKC:-Kf8doC6jaKMEzFRll9I:b3lnrzr) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/81e60aa953f4e79169582e00c9a283dc6fe46c64/View.js#L22)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I can't remember why I did, I can remove them and see if they still function.
</blockquote></details>

I'm thinking that I just copied and pasted it like that from the old components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[View.js, line 22 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-Kf8a0s2ZFzMFvpkPdKC:-Kf8eqld5ReJWnKFiZBX:b13nmck) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/81e60aa953f4e79169582e00c9a283dc6fe46c64/View.js#L22)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm thinking that I just copied and pasted it like that from the old components.
</blockquote></details>

OK, no problem. I'm not sure but i think you don't need to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46)*

**Comment by klappy** [comment]
*[View.js, line 22 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-Kf8a0s2ZFzMFvpkPdKC:-Kf8nL0QZwx771YGvjkT:b-zhwgok) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/81e60aa953f4e79169582e00c9a283dc6fe46c64/View.js#L22)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

OK, no problem. I'm not sure but i think you don't need to.
</blockquote></details>

they work just fine without them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46)*

**Comment by ihoegen** [comment]
This looks good to me, I'll let @mannycolon give the final word though. I'm assuming we'll have to add VerseCheck as a submodule also?

---

Reviewed 9 of 11 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/46#-:-KfA7F0KGXweF3uEUWXh:b-g9aftw)*

**Comment by mannycolon** [comment]
@ihoegen yes we have to add it as a submodule  and probably removed comment Box and proposed Changes once @klappy makes a PR on translatioNotes as well.

**Comment by mannycolon** [comment]
Adding this to the submodules in tC repo should actually be part of this PR 
@klappy @ihoegen what do you think ?

**Comment by ihoegen** [comment]
@mannycolon I will add the submodule to the repo after this PR is merged, along with the one on https://github.com/translationCoreApps/VerseCheck and https://github.com/translationCoreApps/translationNotes_Check_plugin/

**Pull request merged**
