### PR TITLE
Change Translation Words To Important Words

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/26)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[FetchData.js, line 19 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/26#-KbrdzOu4XfYwCzD6Vgu:-KbrdzOu4XfYwCzD6Vgv:bdqf8kb) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/e86ce4b7e9847d8139da955756219fe3f4b0954a/FetchData.js#L19)):*
> ```JavaScript
> // User imports
> const Door43DataFetcher = require('./js/Door43DataFetcher.js');
> const ImportantWordsFetcher = require('./translation_words/ImportantWordsFetcher.js');
> ```

I believe in this case you do want to keep translationWordsFetcher since it is actually fetching fromtransaltionWords (in this case not the tool but the data source)

---

*[FetchData.js, line 37 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/26#-KbreBtxAmYSAvwB7e3I:-KbreBtxAmYSAvwB7e3J:b3n98nb) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/e86ce4b7e9847d8139da955756219fe3f4b0954a/FetchData.js#L37)):*
> ```JavaScript
> 
>   function parseDataFromBook(bookData) {
>     var tWFetcher = new ImportantWordsFetcher();
> ```

same as above if you're not sure maybe ask klappy and/or Ian about this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/26)*

**Comment by mannycolon** [comment]
@RoyalSix Maybe we want to ask thomas for the new icons and banner images

**Comment by mannycolon** [comment]
@RoyalSix i updated the icon images. thomas sent it to me just now

**Comment by RoyalSix** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[FetchData.js, line 19 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/26#-KbrdzOu4XfYwCzD6Vgu:-KbwAAnAgNFep6vNncm0:b-896fix) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/e86ce4b7e9847d8139da955756219fe3f4b0954a/FetchData.js#L19)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I believe in this case you do want to keep translationWordsFetcher since it is actually fetching fromtransaltionWords (in this case not the tool but the data source)
</blockquote></details>

Done.

---

*[FetchData.js, line 37 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/26#-KbreBtxAmYSAvwB7e3I:-KbwABSty2lIslphCd3F:b-896fix) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/e86ce4b7e9847d8139da955756219fe3f4b0954a/FetchData.js#L37)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same as above if you're not sure maybe ask klappy and/or Ian about this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/26)*

**Comment by mannycolon** [comment]
Reviewed 2 of 6 files at r2.
Review status: 7 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/26)*

**Pull request merged**
