### PR TITLE
Updates to get Reducer Props rendering properly

### PR DESCRIPTION
**Pull request by klappy**
## This PR addresses:
Updates to get Reducer Props rendering properly

## Testing:
Will require updating App, ScripturePane, translationWords, VerseCheck to the branch of the same name: `feature/update-reducer-props`

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords_check_plugin/54)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Container.js, line 34 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/54#-KgWvRkLhB5_d-LrDJOH:-KgWvRkLhB5_d-LrDJOI:br4l38x) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/05a2c0c73b6c4ebaa088329d415d89d615b2d14e/Container.js#L34)):*
> ```JavaScript
>     };
>     ScripturePaneFetchData(addNewBible, addNewResource, props, progress, setModuleSettings);
>     // TranslationHelpsFetchData(progress);
> ```

any reason we are commenting this out?

---

*[Container.js, line 169 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/54#-KgWvVkAOro2AnJIYmUZ:-KgWvVkAOro2AnJIYmU_:beh7wk6) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/05a2c0c73b6c4ebaa088329d415d89d615b2d14e/Container.js#L169)):*
> ```JavaScript
> 
>   render() {
>     console.log("tW Container.js", this.props)
> ```

do we still need this console log?

---

*[View.js, line 21 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/54#-KgWviCSvlNqUh43CjzC:-KgWviCSvlNqUh43CjzD:b-d6kdxy) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/05a2c0c73b6c4ebaa088329d415d89d615b2d14e/View.js#L21)):*
> ```JavaScript
>     } = this.props.modules;
> 
>     let scripturePane = <div></div>
> ```

could we add some comments explaining why we are doing this with scripture pane

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/54)*

**Comment by klappy** [comment]
*[Container.js, line 169 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/54#-KgWvVkAOro2AnJIYmUZ:-KgWyD4N90QixmZ-v9rc:bduuewr) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/05a2c0c73b6c4ebaa088329d415d89d615b2d14e/Container.js#L169)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we still need this console log?
</blockquote></details>

No, but it sure helps with debugging :dagger: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/54)*

**Comment by klappy** [comment]
*[Container.js, line 34 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/54#-KgWvRkLhB5_d-LrDJOH:-KgWyHFNViyEPu11xLR_:b-73t44t) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/05a2c0c73b6c4ebaa088329d415d89d615b2d14e/Container.js#L34)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

any reason we are commenting this out?
</blockquote></details>

It doesn't function at all. The way it is called does not pass enough params. Instead of updating another repo, I commented it out until somebody can make it work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/54)*

**Comment by klappy** [comment]
*[View.js, line 21 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/54#-KgWviCSvlNqUh43CjzC:-KgWyTdpcyRT1LBqJO_b:b-v05l95) ([raw file](https://github.com/translationcoreapps/translationwords_check_plugin/blob/05a2c0c73b6c4ebaa088329d415d89d615b2d14e/View.js#L21)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

could we add some comments explaining why we are doing this with scripture pane
</blockquote></details>

Sure, there is a good reason, it's a trick I learned to handle the way react and redux async populates props. They start out blank when they first render the component. this way we don't have to have complex logic deep in the component to look for the data if it exists. we render a blank component if the required data isn't there yet and then render it if the required data is... hence the if statement below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords_check_plugin/54)*

**Pull request merged**
